### ISSUE TITLE
Нет контроля правильности хода фигур

### ISSUE THREAD

**Issue by anei** [bolknote/SedChess#2]
Слон чёрных может двигаться по вертикали.
Лог игры (написал ручками, поскольку chess.log пустой, 1 - белые, 2 - черные):

1: e2 e4
2: h7 h5
1: g1 f3
2: h5 h4
1: g2 g4
2: h4 h3
1: f3 g1
2: g7 g5
1: f1 h3 - взял пешку слоном
2: h8 h3 - взял слона ладьёй
1: g1 h3 - взял ладью конём
2: f7 f5
1: h3 g5 - взял пешку конём
2: f5 f4
1: b1 c3
2: f4 f3
1: g5 f3 - взял пешку конём
2: f8 f3 - взятие коня слоном

Если попробовать совершить заведомо некорректный ход пешкой через всё поле, игра завершается, однако ход на одну клетку по диагонали без взятия вражеской пешки проходит успешно.

**Comment by bolknote** [comment]
Да, контроля нет, я его и не планировал делать :)
