### ISSUE TITLE
Пропуск хода + сьедание фигуры

### ISSUE THREAD

**Issue by kutsy** [bolknote/SedChess#7]
Спасибо за прекрасную игру на sed'e!

Описание проблемы:
Если написать неверный путь, например в самом начале h2h1, то выйдет пропуск хода. На дальнейших стадиях игры можно просто ходить поверх фигур.

**Comment by bolknote** [comment]
Добрый день!

У меня это недокументированный недостаток — ход человека не контролируется никак :) Конечно, можно это дописать, но станет ещё медленее :)
